apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: streamlit-proxy
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 8501
      nodePort: 30008

